baseURL = "https://https://dacacioa.github.io/blog/"
languageCode = "es-es"
title = "Tu Blog"
theme = "PaperMod"

canonifyURLs = false
relativeURLs = false


[params]
  ShowReadingTime = true
  ShowToc = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30


